# Generated by Django 4.0.5 on 2022-07-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0003_auto_20220611_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='RouteConnections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_stops.routes')),
                ('stops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_stops.busstops')),
            ],
            options={
                'db_table': 'route_connection',
            },
        ),
        migrations.AddField(
            model_name='busstops',
            name='route',
            field=models.ManyToManyField(through='bus_stops.RouteConnections', to='bus_stops.routes'),
        ),
    ]
