# Generated by Django 3.2.5 on 2022-06-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=30, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=30, max_digits=30)),
            ],
            options={
                'db_table': 'bus_stops',
            },
        ),
    ]
