# Generated by Django 3.2.5 on 2022-06-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus_stops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=30, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=30, max_digits=30)),
            ],
            options={
                'db_table': 'stops',
            },
        ),
    ]
