# Generated by Django 3.2.5 on 2022-06-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstops',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='busstops',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
