# Generated by Django 3.2.5 on 2022-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stops', '0002_auto_20220611_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstops',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='busstops',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
