# Generated by Django 3.2.5 on 2022-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=19)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
            options={
                'db_table': 'bus_stops',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('weather', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'current_weather',
            },
        ),
    ]
